# -*- coding: utf-8 -*-
"""ENTREGA 04 - NGNF.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MYKj0QunVl2O0kL-W2cub1P8RzagZB7

Para esta etapa, uniremos las tres bases de datos que cada uno de los integrantes limpió por separado en la entrega 02 de nuestro proyecto. Así lograremos tener una única base de datos final en la que podamos trabajar para la entrega 04 y, con esa base final, estableceremos el punto de partida para que cada uno realice su visualización individual.
"""

import pandas as pd

#Agregamos las rutas de nuestras bases de datos por año
base_2020 = '/content/drive/MyDrive/NARRACIÓN GRÁFICA DE NO FICCIÓN/base_2020.csv'
base_2021 = '/content/drive/MyDrive/NARRACIÓN GRÁFICA DE NO FICCIÓN/base_2021.csv'
base_2022 = '/content/drive/MyDrive/NARRACIÓN GRÁFICA DE NO FICCIÓN/base_2022.csv'

#Leemos los archivos CSV en DataFrames
df1 = pd.read_csv(base_2020)
df2 = pd.read_csv(base_2021)
df3 = pd.read_csv(base_2022)

#Agregamos la columna "año" con los valores correspondientes
df1['año'] = 2020
df2['año'] = 2021
df3['año'] = 2022

#Unimos los DataFrames por filas
df_final = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

#Revisamos cómo es que se ve
print(df_final)

#Guardamos nuestra base de datos final en nuestro Drive
ruta_guardar = '/content/drive/MyDrive/NARRACIÓN GRÁFICA DE NO FICCIÓN/base_de_datos_final.csv'
df_final.to_csv(ruta_guardar, index=False)