# -*- coding: utf-8 -*-
"""ENTREGA 04 - NGNF.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10MYKj0QunVl2O0kL-W2cub1P8RzagZB7

Con respecto a mi visualización, utilizaré la base de datos final que unimos y trabajamos junto a mis compañeros. En mi caso, espero crear un gráfico que permita distinguir en qué países se escucha más música urbana en relación a los años.
"""

import altair as alt
import pandas as pd
from google.colab import files

#Leemos la base de datos final
base_de_datos_final = '/content/drive/MyDrive/NARRACIÓN GRÁFICA DE NO FICCIÓN/base_de_datos_final.csv'
df = pd.read_csv(base_de_datos_final)

#Filtramos los datos "global" de la columna "País", ya que para mi caso, quiero trabajar con los datos solo de los países por si solos
df_filtrado = df[df['País'] != 'Global']

#Convertimos la primera letra de cada país a mayúscula
df_filtrado['País'] = df_filtrado['País'].str.capitalize()

#Calculamos el total de transmisiones por año y por país
total_transmisiones = df_filtrado.groupby(['año', 'País'])['streams'].sum().reset_index()

#Creamos un gráfico de barras interactivo con Altair usando el DataFrame del total de transmisiones por año y por país
chart = alt.Chart(total_transmisiones).mark_rect().encode(
    x=alt.X('año:O', title="Año"),
    y=alt.Y('País:N', title="País"),
    color=alt.Color('streams:Q', title="Transmisiones", scale=alt.Scale(scheme="purples")), #En color, seguimos trabajando con la misma paleta de colores
    tooltip=[
        alt.Tooltip("año", title="Año"),
        alt.Tooltip("País", title="País"),
        alt.Tooltip("streams", title="Transmisiones"),
    ],
).configure_view(strokeWidth=0).properties(width=400, title="Transmisiones por país y año", background="white").interactive()

#Guardamos el gráfico localmente en formato HTML
output_path = '/content/gráfico_martina.html'
chart.save(output_path)

#Descargamos el archivo localmente
files.download(output_path)

