# -*- coding: utf-8 -*-
"""ENTREGA 02 - NGN. 02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ELhh0YTtx2iUdHbHAknkjQdgB6lDr2AM

Combinamos las nueve bases de datos que previamente limpiamos por separado (Chile, Colombia, Argentina, Perú, Guatemala, Honduras, México, España y Top Global) con el objetivo de trabajar con una única base de datos. Sin embargo, hemos asegurado que sea posible distinguir cada conjunto de datos agregando una columna de identificación.
"""

import pandas as pd

#Ruta de los archivos CSV
CSV_países = "/content/drive/MyDrive/BASES DE DATOS/"

#Creamos una lista con los nombres de los archivos CSV que se encuentran en nuestro Drive
filenames = ["Argentina_2022_limpio.csv", "Chile_2022_limpio.csv", "Colombia_2022_limpio.csv",
             "Perú_2022_limpio.csv", "Guatemala_2022_limpio.csv", "Honduras_2022_limpio.csv",
             "México_2022_limpio.csv", "España_2022_limpio.csv", "Global_2022_limpio.csv"]

#Creamos una lista vacía para almacenar los DataFrames
dataframes = []

#Leemos los archivos CSV y los añadimos a la lista
for filename in filenames: #"for" para hacer un buble y recorrer la lista de los nombres de los archivos filenames
    df = pd.read_csv(f"{CSV_países}{filename}") #En cada iteración, leemos un archivo CSV específico usando "pd.read_csv()", lo convertimos en un DataFrame y lo almacenamos en la lista dataframes.
    dataframes.append(df)
    #Agregamos una columna con el nombre del archivo al DataFrame actual, para identificar de que país viene cada dato
    df["país"] = filename

#Unimos los DataFrames para trabajar con ellos todos juntos
df_merged = pd.concat(dataframes, ignore_index=True) #Utilizamos "pd.concat()" para unir todos los DataFrames almacenados en la lista dataframes en un solo DataFrame llamado "df_merged". La opción "ignore_index=True" reinicia los índices para que sean secuenciales.

#Finalmente, guardamos todo en nuestro Drive personal
df_merged.to_csv("/content/drive/MyDrive/BASES DE DATOS/base_de_datos_original.csv", index=False)